var phrases = [
    // CONJUNCTIONS
    "and",
    "if",
    "even if",
    // WH- ADVERBS
    "who",
    "what",
    "where",
    "why",
    "when",
    // SALUTATIONS
    "hello",
    "hey",
    "hi",
    "bye",
    "goodbye",
    "good bye",
    "good-bye",
    "see you later",
    "good morning",
    "good afternoon",
    "good evening",
    "goodnight",
    "good night",
    "g'night",
    // AFFIRMATIONS, NEGATIONS, THANKS, APOLOGIES
    "yes",
    "yeah",
    "certainly",
    "of course",
    "of course not",
    "congrats",
    "congratulations",
    "thanks",
    "thank you",
    "thank you very much",
    "thanks a lot",
    "I'm sorry",
    "sorry",
    "nevermind",
    "never mind",
    // TIME
    "now",
    "right now",
    "not now",
    "not ever",
    "later",
    "later on",
    "today",
    "tomorrow",
    "yesterday",
    "anytime",
    "always",
    "often",
    "sometime",
    "sometimes",
    "never",
    // LOCATION
    "here",
    "there",
    "over here",
    "over there",
    "right here",
    "right there",
    "everywhere",
    "anywhere",
    "nowhere",
    "somewhere",
    // PREPOSITIONS
    "aboard",
    "above",
    "across",
    "across from",
    "after",
    "again",
    "against",
    "ahead of",
    "along",
    "alongside",
    "among",
    "amongst",
    "as far as",
    "as soon as",
    "as well as",
    "atop",
    "because",
    "because of",
    "before",
    "behind",
    "below",
    "beneath",
    "beside",
    "besides",
    "between",
    "beyond",
    "close",
    "close to",
    "closer",
    "closer to",
    "closest",
    "closest to",
    "down",
    "during",
    "except",
    "except for",
    "far",
    "far from",
    "farther",
    "farther from",
    "farthest",
    "farthest from",
    "further",
    "further from",
    "furthest",
    "furthest from",
    "in front of",
    "inside",
    "inside of",
    "instead of",
    "left of",
    "near",
    "near to",
    "nearer",
    "nearest",
    "next to",
    "off",
    "on",
    "on top of",
    "other than",
    "outside",
    "outside of",
    "over",
    "right of",
    "since",
    "such as",
    "thanks to",
    "through",
    "throughout",
    "toward",
    "towards",
    "under",
    "underneath",
    "until",
    "up",
    "up to",
    "versus",
    "while",
    "with",
    "within",
    "without"
]

function capitalizeFirstLetter(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
}

var keys = {}

phrases.forEach(phrase => {    
    keys[phrase] = {}
    keys[phrase]["en"] = phrase
})

exports.keys = keys